# Generated by Django 3.1.7 on 2021-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('SubscriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('SubscriptionName', models.CharField(max_length=100)),
            ],
        ),
    ]
